### PR TITLE
Dataset selection

### PR DESCRIPTION
**Pull request by vinjana**
Branch is based on `improved-table` branch.
Datasets are selected in `selectedDatatets` variable.

Next steps are

 * fix checkbox display (currently above identifier)
 * map selected datasets to DACs. Provide 
```javascript
{
   $dacId: { 
      // all DAC data
      selectedDatasets: [ $listOfDatasetsForDac ]
   }
}
```

This data can then be used to compose a submission email.

### CODE REVIEW

**Comment by vinjana** [comment]
I am working on getting this into a structure

```json
[
  { 
     { // dac JSON
       datasets: [ // dataset JSONS ]
  },
 ...
]
```

This will soon be finished and the results can then be displayed in a table with the submission form ("what you selected") and could be added to the submission email.

Do you already have an idea of how to add a template email to the submission button?

**Comment by KochTobi** [comment]
Yes working on it. Regarding the life update in the form i thought about writing a function that is triggered by a checkbox's action and append / removes the information from the form.

**Comment by vinjana** [comment]
Putting stuff in a class is certainly a good idea, but I am currently not sure how to do that. I didn't get to ES2015. If the code is reused after this prototype it may be worth the effort, but I am not sure it is so pressing in the moment, as there is a chance that all this will be thrown away.

**Comment by KochTobi** [comment]
> Putting stuff in a class is certainly a good idea, but I am currently not sure how to do that. I didn't get to ES2015. If the code is reused after this prototype it may be worth the effort, but I am not sure it is so pressing in the moment, as there is a chance that all this will be thrown away.

True. But we should keep this in mind in case it isn't thrown away.

**Comment by vinjana** [comment]
I agree, but also is not yet an awful lot of code. So I guess that namespace pollution is not yet an issue.

**Pull request merged**
